   add.l   a2,d5           ;pOEP
   move.l  d0,d3           ;sOEP
   and.l   d1,d5           ;pOEP
   move.b  (a0,d6.l*4),d3  ;sOEP
   move.l  d5,d6           ;pOEP
   lsr.l   #8,d6           ;sOEP
   add.w   d4,d0           ;pOEP
   lsl.w   #8,d6           ;sOEP
   move.b  (a1,d3.l),d3    ;pOEP
   lsr.l   #8,d6           ;sOEP
   move.b  d3,(a3)+        ;pOEP
   subq.w  #1,d7           ;sOEP
   bne.b   .loop           ;free
