        move.l  #$ffff,d7
        moveq   #16,d6
        move.l  d0,d2
        asr.l   d6,d2
        and.l   d7,d0
        move.l  d1,d4
        asr.l   d6,d4
        and.l   d7,d1
        move.l  d0,d3
        mulu.w  d1,d3
        move.l  d3,d5
        lsr.l   d6,d5
        muls.l  d2,d1
        add.l   d5,d1
        move.l  d1,d5
        and.l   d7,d5
        muls.l  d4,d0
        add.l   d5,d0
        muls.l  d4,d2
        asr.l   d6,d1
        add.l   d1,d2
        move.l  d0,d1
        asr.l   d6,d1
        add.l   d1,d2
        lsl.l   d6,d0
        and.l   d7,d3
        add.l   d3,d0

